services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - 4dstack-app:latest
    user: vscode
    volumes:
<<<<<<< HEAD
      - ../:/workspaces/4dstack:cached
=======
      - ../:/workspaces/CamOnDagster:cached
>>>>>>> 21c38e0 (Updating another Dagster Asset to use IO Manager)
    environment:
      - DLT_TELEMETRY=off
      - DBT_PROFILES_DIR=/workspaces/4dstack/dbt
    working_dir: /workspaces/4dstack
    networks:
      - dagster-net

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=dagster
      - POSTGRES_PASSWORD=dagster
      - POSTGRES_DB=dagster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U 'dagster' -d 'dagster'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dagster-net

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=dagster
      - POSTGRES_PASSWORD=dagster
      - POSTGRES_DB=dagster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U 'dagster' -d 'dagster'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dagster-net

volumes:
  postgres_data:
<<<<<<< HEAD

=======
>>>>>>> aae1518 (Done! Slim CI!)


networks:
  dagster-net:
    driver: bridge
