name: Continuous Integration


# Trigger this workflow on push or pull_request events
on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  pull_request:
    branches:
      - main  # Runs when creating a pull request to the main branch


jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.12'  # or whatever version you use


      # Step 3 Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      # Step 5: Install DBT package dependencies
      - name: Install DBT dependencies
        run: |
          cd dbt && dbt deps